### ISSUE TITLE
Does the speaker embedding conditioning work?

### ISSUE THREAD

**Issue by BangjianZhou** [p0p4k/vits2_pytorch#15]
https://github.com/p0p4k/vits2_pytorch/blob/c4fb23c06fadf8a8fc49b57a0aa7ebdfe744bb0f/models.py#L847

Hi, just wonder this line. Seems that though the TextEncoder conditioned on speaker embedding on the 3rh layer, but the g is not feed into the TextEncoder? Did I misunderstand sth?

**Comment by p0p4k** [comment]
Thanks a lot for catching it, I fixed it in latest patch! Was too focused on single speaker training that I forgot to enable that part.
