### ISSUE TITLE
This is not an issue but results of using vits2_pytorch

### ISSUE THREAD

**Issue by athenasaurav** [p0p4k/vits2_pytorch#17]
Thanks to the contributors of this repo. @p0p4k and others. 

Here is a [samples](https://drive.google.com/drive/folders/16Pvm48wUMIHcN2IdhPIGLFi7HAycoE8H?usp=sharing) of Voice generated using a custom dataset in LJSpeech Format. 

The model ckpts used was G_70000.pth which is so early. Trained on a 2V100 Engine.

**Comment by p0p4k** [comment]
... videos ... =D

**Comment by p0p4k** [comment]
Thanks bhai, @athenasaurav!  I was going to contact you after confirming few more things in the code. Is it okay to add these samples on main page of this repo?

**Comment by athenasaurav** [comment]
Of course please add these. I m still training and will keep adding more samples to the same drive link drive. Also would love to connect with you whenever you feel so.
