### ISSUE TITLE
Is there any Huggingface url link for the model？

### ISSUE THREAD

**Issue by dsp6414** [p0p4k/vits2_pytorch#2]
I appreciate it.

**Comment by dsp6414** [comment]
tks

**Comment by p0p4k** [comment]
@dsp6414 We have no trained weights for this architecture yet. If anyone from the community is willing to help, it will  be great. I can train on my GPU after 2 weeks.

**Comment by p0p4k** [comment]
@athenasaurav Thank you for the offer. I will email you as soon as the initial run of this code is bug-free. Thanks again!

**Comment by athenasaurav** [comment]
Sure @p0p4k looking forward to it.
