### ISSUE TITLE
log_w_ not detach

### ISSUE THREAD

**Issue by hdmjdp** [p0p4k/vits2_pytorch#21]
https://github.com/p0p4k/vits2_pytorch/blob/cf513a71e07aed48448e582eaecfaef2a2b8d6b6/train_ms.py#L265

true duraion should not detach

**Comment by p0p4k** [comment]
> https://github.com/p0p4k/vits2_pytorch/blob/cf513a71e07aed48448e582eaecfaef2a2b8d6b6/train_ms.py#L265
> 
> true duraion should not detach

Why not? It is not supposed to carry any gradients to the main net_g model. Also, I believe that logw itself doesn't have any gradients, since it is calculated in MAS attn. So, detach or not should not make difference. Am I missing something?

**Comment by hdmjdp** [comment]
> > https://github.com/p0p4k/vits2_pytorch/blob/cf513a71e07aed48448e582eaecfaef2a2b8d6b6/train_ms.py#L265
> > 
> > true duraion should not detach
> 
> Why not? It is not supposed to carry any gradients to the main net_g model. Also, I believe that logw itself doesn't have any gradients, since it is calculated in MAS attn. So, detach or not should not make difference. Am I missing something?

As you said, detaching the true label has no meaning.

**Comment by p0p4k** [comment]
But `w` has gradients as seen in this [code](https://github.com/p0p4k/vits2_pytorch/blob/cf513a71e07aed48448e582eaecfaef2a2b8d6b6/models.py#L855C4-L871C20). We use with no grad to temporarily remove the gradients.
