### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by CCludts** [p0p4k/vits2_pytorch#40]
Hi.

First of all, thanks for your contributions on VITS2!

I was wondering if you'd have any tips how to train a different (English) voice than the ljspeech one. I don't have access to very powerful GPUs, so it'd great if it were possible to do fine-tuning on top of the 64k steps checkpoint that you've already posted (again, thanks!).
Possibly something similar to https://github.com/nivibilla/efficient-vits-finetuning?

**Comment by Subarasheese** [comment]
You could simply apply RVC over the generated audio, or in case you really want it to have a different voice as-is, you could convert all audio samples from ljspeech to another voice using RVC.
