### ISSUE TITLE
KeyError when training the Chinese dataset

### ISSUE THREAD

**Issue by KevinWang676** [p0p4k/vits2_pytorch#53]
Hi, does anyone know how to fix the `KeyError: ','` when training the Chinese dataset? I'm using `chinese_cleaners` defined [here](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/text/cleaners.py#L32C5-L32C21). Thank you!

![image](https://github.com/p0p4k/vits2_pytorch/assets/126712357/5870f092-e90f-483a-83ff-3d638f199f47)

**Comment by p0p4k** [comment]
fixed in latest patch. 
unavailable tokens will just be skipped.

**Comment by KevinWang676** [comment]
Hi, thank you so much for the fix! However, you may need to change the variable to `cleaned_text` in line 40 and define `sequence = []` in line 38. I fix the typos in my [folk](https://github.com/KevinWang676/VITS2-Mandarin/blob/main/text/__init__.py#L38).

Also, I wonder if missing the symbols like the comma `,` would affect my training process and results. Thank you!

**Comment by KevinWang676** [comment]
Hi @p0p4k, I wonder if missing some symbols like the comma `,` would affect my training process and results. Thank you!

**Comment by p0p4k** [comment]
You can add missing punctuations in the punctuations list and try training with that first.
