### ISSUE TITLE
New feature: Deleting the old .pth files when training

### ISSUE THREAD

**Issue by KevinWang676** [p0p4k/vits2_pytorch#56]
Hi, I found that there was no funtion to delete the existing `.pth` files, which made the training process require a lot of space. So it would be very helpful if you can add a function to deleting the previous `.pth` files when training. Thanks!

**Comment by p0p4k** [comment]
> Hi, I found that there was no funtion to delete the existing `.pth` files, which made the training process require a lot of space. So it would be very helpful if you can add a function to deleting the previous `.pth` files when training. Thanks!

Yes, I am planning on making a function that keeps the top k best checkpoints based on Mel loss metric.

**Comment by KevinWang676** [comment]
Great, thank you!

**Comment by p0p4k** [comment]
Solved in #62
