### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by KevinWang676** [p0p4k/vits2_pytorch#57]
Hi, I was using `cjke_cleaners2` to clean the texts. However, I got the error `ValueError: too many values to unpack (expected 2)` as shown below 

![image](https://github.com/FENRlR/MB-iSTFT-VITS2/assets/126712357/96bbcbc6-b0a6-4407-b968-c1ac3a5c4e92)

But I don't think I got more than 2 values to unpack. Here is the structure of my cleaned texts

![image](https://github.com/FENRlR/MB-iSTFT-VITS2/assets/126712357/e2c0f8b7-7ef1-4422-ab41-54bf726c6143)

So I wonder which step could go wrong. Thank you!

**Comment by p0p4k** [comment]
Can you go to the filter function and before the `for` statement, print out `self.audiopaths_and_text` ?

**Comment by KevinWang676** [comment]
Thanks for your reply! I printed out `self.audiopaths_and_text`, but I didn't see why it went wrong. It seems that the audiopaths and text are split correctly. Thanks.

![image](https://github.com/p0p4k/vits2_pytorch/assets/126712357/56ae1e7d-cc66-4c9b-ab0b-dd27f9038074)

**Comment by KevinWang676** [comment]
Sorry, this issure is due to some unexpected symbols in my texts such as `{`, `#`, and `<`. Thank you!

**Comment by p0p4k** [comment]
Good luck! Share your sound quality results after training is done!

**Comment by KevinWang676** [comment]
Thank you. Happy holidays! I'm start the training, and I wonder if a custom dataset that contains one-hour speech would work. I think it might be a little bit small.
