### ISSUE TITLE
DurationDiscriminatorType error

### ISSUE THREAD

**Issue by lpscr** [p0p4k/vits2_pytorch#64]
Hi there thank you for all this amazing work ! I really loved it when I tested it a few days ago, and it was working perfectly. However, today, when I tried the new version, I encountered some issues

 just wanted to point out something I noticed in your code, specifically in the train.py script. It looks like you're doing some wrong there! The line where you define DurationDiscriminator

in file train.py line 168-170
DurationDiscriminator = AVAILABLE_DURATION_DISCRIMINATOR_TYPES[duration_discriminator_type]
        
net_dur_disc = DurationDiscriminator(

the DurationDiscriminator  return str and not the class for DurationDiscriminator  

also i notice the json miss the new 

"duration_discriminator_type" :"dur_disc_2",
other get error 
in files

vits2_ljs_base.json and 
vits2_ljs_base_nospd.json

i fix json and when it's run the train.py get this i error return str in DurationDiscriminator like i say up

can you please explain the differences between 'dur_disc_1' and 'dur_disc_2' and recommend which one is preferable? in this new option or need to see my self what work best ? i am very  beginner on this stuff  and all this new to me,

Keep up the great work :)

**Comment by p0p4k** [comment]
Can you let me know what the exact error is? (a screenshot maybe)

**Comment by lpscr** [comment]
hi i run colab for example this
https://colab.research.google.com/drive/12iCPWMpKdekM6F1HujYCh5H8PyzrgJN2?usp=sharing

i fix some parts to make work  like install espeak
and fix some path 
and when i run last cell train

i get this error


![1](https://github.com/p0p4k/vits2_pytorch/assets/147736764/46d3b6c5-7454-4723-b554-4fed47b5361e)

then i fix the json file add the miss "duration_discriminator_type" :"dur_disc_2",

then i run again an then i get 

![2](https://github.com/p0p4k/vits2_pytorch/assets/147736764/65d71e3d-bc14-45ba-9106-ee3f57de6a3b)

i hope this help 
thank you very much

**Comment by p0p4k** [comment]
Hi, I made a quick fix, let me know if it works. I will make a better fix later on if needed. Thanks.

**Comment by lpscr** [comment]
Thank you very much working !!! great now 

only you need to add in json config the miss 
"duration_discriminator_type" :"dur_disc_2",
and then working 

![3](https://github.com/p0p4k/vits2_pytorch/assets/147736764/93eb9c09-0d5d-4ff5-8359-3979d436fa70)

can you please explain the differences between 'dur_disc_1' and 'dur_disc_2' and recommend which one is preferable?

**Comment by p0p4k** [comment]
https://github.com/p0p4k/vits2_pytorch/issues/59
