### ISSUE TITLE
how to know whether the model is  fitting 

### ISSUE THREAD

**Issue by creed2415** [p0p4k/vits2_pytorch#66]
based on these metrics（[loss_disc, loss_gen, loss_fm, loss_mel, loss_dur, loss_kl,global_step, lr]） in the log

**Comment by p0p4k** [comment]
I would look at loss_mel, loss_dur, loss_kl.
loss_mel is reconstructed wav's mel and real mel difference.
loss_dur is aligner and dur_pred difference.
loss_kl is the distance between p(z_mel | mel) and p(z_mel | text)

**Comment by a5a5aa555oo** [comment]
You can try this driver, it works great with RTL8188GU.

https://github.com/a5a5aa555oo/rtl8xxxu
