### ISSUE TITLE
Keep training on existed checkpoint

### ISSUE THREAD

**Issue by HuuHuy227** [p0p4k/vits2_pytorch#76]
Hi, your repo is awesome. I want to know how could i keep training on an existed checkpoint. I can't find any config show that way.

**Comment by p0p4k** [comment]
See in train.yaml under configs folder.

**Comment by p0p4k** [comment]
I think the same model name (-m) resumes the training.

**Comment by JohnHerry** [comment]
> Hi, your repo is awesome. I want to know how could i keep training on an existed checkpoint. I can't find any config show that way.

Do you mean to keep the schedulers saved into checkpoint and then loaded during resume from the checkpoint?

**Comment by HuuHuy227** [comment]
> > Hi, your repo is awesome. I want to know how could i keep training on an existed checkpoint. I can't find any config show that way.
> 
> Do you mean to keep the schedulers saved into checkpoint and then loaded during resume from the checkpoint?

Yes. I mean that I had a checkpoint I've trained before and now I want to continue train on that checkpoint.
