### ISSUE TITLE
model compute error

### ISSUE THREAD

**Issue by pipijiev12** [p0p4k/vits2_pytorch#8]
RuntimeError: Given groups=1, weight of size [192, 80, 1], expected input[64, 513, 297] to have 80 channels, but got 513 channels instead
After I preprocessed the data, everything went fine. However, model calculation problems arise during the training process. Is it because I preprocessed the data wrong?

**Comment by p0p4k** [comment]
@pipijiev12 Hi, it should be fixed in the latest patch. Thanks for letting me know! It is because we are using 80 channel mel spectrogram in this architecture instead of 513 channels linear spec that VITS-1 uses. I had a typo in data_utils.py, I believe the problem should be fixed now.
