### ISSUE TITLE
Why are you using "use_mel_posterior_encoder"?

### ISSUE THREAD

**Issue by Moon-sung-woo** [p0p4k/vits2_pytorch#89]
Hi I'm sungwoo Moon.
First of all, thank you for your sharing your code.

I'm looking at your code and I'm wondering why you use 'use_mel_posterior_encoder'.
In the paper vits1, it says that we use spectrogram like vits1, but I wonder if there is a difference in TTS performance.

Thank you.

**Comment by p0p4k** [comment]
In paper they said they use Mel spec, while vits1 uses linear spec. Am I missing something? 🧐

**Comment by lastapple** [comment]
> In paper they said they use Mel spec, while vits1 uses linear spec. Am I missing something? 🧐

So is there a big difference between the effects of these two conditions?

**Comment by p0p4k** [comment]
I think better to use linear spectrogram. But it's not a big deal

**Comment by Moon-sung-woo** [comment]
@p0p4k Oh! i'm sorry. I read the paper wrong.
Thank you
